### PR TITLE
allow multiple named exports

### PR DESCRIPTION
**Pull request by dnakov**

### CODE REVIEW

**Comment by developit** [comment]
Are you sure this changes anything? I don't see how it could have worked without `/g` which makes me second guess this regex, haha.

**Comment by dnakov** [comment]
Well, it worked if you only had 1 `export`
I needed moar :)
screen shot 2018-01-22 at 6 12 39 pm

**Comment by developit** [comment]
Makes sense! Thought my demo checked that but I looked and it doesn't. Good catch.

**Comment by developit** [comment]
Released as [0.1.6](https://github.com/developit/workerize/releases/tag/0.1.6)!

**Pull request merged**
